[package]
name = "santa-claus"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Lienbacher <lienbacher.tom@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-graph = "0.21"
