[package]
name = "santa-claus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-graph = "0.21"
mcmf = "2.0.0"
